version: "3.6"

services:

  php:
    tty: true
    build:
      context: ../../code/app
      dockerfile: ../../ops/docker/php/dev/Dockerfile
    volumes:
      - ../../code/app:/app
      - ../../ops:/ops
      - ../../.git:/.git
      - ~/.ssh:/root/.ssh
    ports:
      - "8080:80"
    restart: on-failure
    depends_on:
      - database
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=verysecretpass
    restart: always
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=verysecretpass
      interval: 5s
      timeout: 10s
      retries: 5

  vue:
    build:
      context: ../../code/frontend
      dockerfile: ../../ops/docker/vue/dev/Dockerfile
    tty: true
    volumes:
      - ../../code/frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "80:8080"
    restart: always

volumes:
    db:
    node_modules: